#spring:
#  jpa:
#    generated-ddl: true
#    hibernate:
#      ddl-auto: true
#      show_sql: true
#
#cloud:
#  aws:
#    region:
#      static: eu-west-1
#    stack:
#      auto: true
#    rds:
#      dbInstanceIdentifier: userdb
#      springaws:
#        password: 
#        username: gullyipl
#        databaseName: userdb
#    credentials:
#      accessKey: 
#      secretKey: 
#      instanceProfile: true
#      useDefaultAwsCredentialsChain: true
#    s3:
#      bucket: 
